:octocat: :bug: fix execution actions linter exit 1
Just to make sure it doesn't fail

diff --git a/.github/workflows/github-actions-devsecops-test-workflow.yaml b/.github/workflows/github-actions-devsecops-test-workflow.yaml
--- a/.github/workflows/github-actions-devsecops-test-workflow.yaml
+++ b/.github/workflows/github-actions-devsecops-test-workflow.yaml
@@ -34,9 +34,11 @@ jobs:
 
       - name: Generate md report Check workflow files under .github/workflows using linter
         shell: bash
+        # The docker container fails with 1 when findings, so make sure it passes
+        # The exception will come from the problem-matcher below
         run: |
           echo "Preparing the report linter in .md format"
-          docker run -v $(pwd):$(pwd) -w $(pwd) dockerhub.docker.artifactory.viasat.com/rhysd/actionlint:1.6.26 -format '{{range $err := .}}### Error at line {{$err.Line}}, col {{$err.Column}} of `{{$err.Filepath}}`\n\n{{$err.Message}}\n\n```\n{{$err.Snippet}}\n```\n\n{{end}}' > workflows-linter.md
+          docker run -v $(pwd):$(pwd) -w $(pwd) dockerhub.docker.artifactory.viasat.com/rhysd/actionlint:1.6.26 -format '{{range $err := .}}### Error at line {{$err.Line}}, col {{$err.Column}} of `{{$err.Filepath}}`\n\n{{$err.Message}}\n\n```\n{{$err.Snippet}}\n```\n\n{{end}}' > workflows-linter.md || true
           cat workflows-linter.md
 
       - name: Add Lint PR Comment
